fix for using old NULL (which expands to integer value `0`) vs. new `nullptr`:
libassert\include\libassert\expression-decomposition.hpp(59,9): error C2446: '!=': no conversion from 'A' to 'int64_t *'
1>        with
1>        [
1>            A=int
1>        ] (compiling source file simd-imgproc/src/Simd/SimdAvx512bwTexture.cpp)
libassert\include\libassert\expression-decomposition.hpp(59,9): message : Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or parenthesized function-style cast (compiling source file simd-imgproc/src/Simd/SimdAvx512bwTexture.cpp)